DROP TABLE USER;
CREATE TABLE USER (
  ID BIGINT AUTO_INCREMENT,
  FIRST_NAME VARCHAR(255),
  LAST_NAME VARCHAR(255),
  AGE INT,
  
  PRIMARY KEY (ID)
);

DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
